#!/usr/bin/env python3
"""
restore_damaged_group.py
Auto-generated script to restore 20 recoverable contacts from the script-LSAM-DAMAGED group.
"""

import os
import sys

# Add project root to path
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Import functions from restore_with_backups
from src.bridge.contact_macos import ContactMacOSBridge
from scripts.restore_with_backups import restore_contact, logger, SESSION_DIR, BACKUP_DIR, log_file

import json

# This payload was generated by analyzing the most recent `-original.txt` and `-original.jpg` backups
RESTORE_TARGETS = [
    {
        "contact_name": "Katia HARDOUIN",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_06-05-54/backups/Katia_HARDOUIN",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_06-05-54/backups/Katia_HARDOUIN/Katia_HARDOUIN-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "canonical_social_handle": "katia-hardouin-6a3a3148",
            "canonical_linkedin_url": "https://www.linkedin.com/in/katia-hardouin-6a3a3148"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Beno\u00eet MARICHEZ",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_00-14-39/backups/Beno\u00eet_MARICHEZ",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_00-14-39/backups/Beno\u00eet_MARICHEZ/Beno\u00eet_MARICHEZ-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_00-14-39/backups/Beno\u00eet_MARICHEZ/Benoi\u0302t_MARICHEZ-original.jpg",
            "canonical_social_handle": "benoitmarichez",
            "canonical_linkedin_url": "https://www.linkedin.com/in/benoitmarichez"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Pierre AUBOUIN",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_AUBOUIN",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_AUBOUIN/M_Pierre_AUBOUIN-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_AUBOUIN/M_Pierre_AUBOUIN-original.jpg",
            "canonical_social_handle": "Pierre%20Aubouin",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Pierre%20Aubouin"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 22_Jul_2015\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Lionel Baraban",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_06-18-27/backups/Lionel_Baraban",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_06-18-27/backups/Lionel_Baraban/Lionel_Baraban-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_06-18-27/backups/Lionel_Baraban/Lionel_Baraban-original.jpg",
            "canonical_social_handle": "lionelbaraban",
            "canonical_linkedin_url": "https://www.linkedin.com/in/lionelbaraban"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Me Nada VILLERMAIN-LECOLIER",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Nada_VILLERMAIN_LECOLIER",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Nada_VILLERMAIN_LECOLIER/Me_Nada_VILLERMAIN_LECOLIER-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Nada_VILLERMAIN_LECOLIER/Me_Nada_VILLERMAIN_LECOLIER-original.jpg",
            "canonical_social_handle": "Villermain-Lecolier%20Nada",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Villermain-Lecolier%20Nada"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 28_Oct_2013\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Philippe Chuzel",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Philippe_Chuzel",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Philippe_Chuzel/Philippe_Chuzel-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Philippe_Chuzel/Philippe_Chuzel-original.jpg",
            "canonical_social_handle": "philippechuzel",
            "canonical_linkedin_url": "https://www.linkedin.com/in/philippechuzel"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Me Anita Iriart-Sorhondo",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Anita_Iriart_Sorhondo",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Anita_Iriart_Sorhondo/Me_Anita_Iriart_Sorhondo-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Anita_Iriart_Sorhondo/Me_Anita_Iriart_Sorhondo-original.jpg",
            "canonical_social_handle": "anitairiartsorhondo",
            "canonical_linkedin_url": "https://www.linkedin.com/in/anitairiartsorhondo"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Philippe HUMEAU",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Philippe_HUMEAU",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Philippe_HUMEAU/M_Philippe_HUMEAU-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Philippe_HUMEAU/M_Philippe_HUMEAU-original.jpg",
            "canonical_social_handle": "philippe%20humeau",
            "canonical_linkedin_url": "https://www.linkedin.com/in/philippe%20humeau"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "David Ring",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-09_13-32-05/backups/David_Ring",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-09_13-32-05/backups/David_Ring/David_Ring-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-09_13-32-05/backups/David_Ring/David_Ring-original.jpg",
            "canonical_social_handle": "davidring1",
            "canonical_linkedin_url": "https://www.linkedin.com/in/davidring1"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Bernard MALACHANE",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-29-03/backups/M_Bernard_MALACHANE",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-29-03/backups/M_Bernard_MALACHANE/M_Bernard_MALACHANE-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-29-03/backups/M_Bernard_MALACHANE/M_Bernard_MALACHANE-original.jpg",
            "canonical_social_handle": "Bernard%20Malachane",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Bernard%20Malachane"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 29_Sep_2011\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Jean-Pierre Bokobza",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_05-34-28/backups/Jean_Pierre_Bokobza",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_05-34-28/backups/Jean_Pierre_Bokobza/Jean_Pierre_Bokobza-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_05-34-28/backups/Jean_Pierre_Bokobza/Jean_Pierre_Bokobza-original.jpg",
            "canonical_social_handle": "jean-pierre-bokobza-a03b8018",
            "canonical_linkedin_url": "https://www.linkedin.com/in/jean-pierre-bokobza-a03b8018"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Me Charlotte HUET HERFRAY",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Charlotte_HUET_HERFRAY",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Charlotte_HUET_HERFRAY/Me_Charlotte_HUET_HERFRAY-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Me_Charlotte_HUET_HERFRAY/Me_Charlotte_HUET_HERFRAY-original.jpg",
            "canonical_social_handle": "Herfray%20Charlotte",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Herfray%20Charlotte"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 22_Aug_2005\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Alexandre DELIVET",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_07-30-08/backups/M_Alexandre_DELIVET",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_07-30-08/backups/M_Alexandre_DELIVET/M_Alexandre_DELIVET-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_07-30-08/backups/M_Alexandre_DELIVET/M_Alexandre_DELIVET-original.jpg",
            "canonical_social_handle": "Alexandre%20Delivet",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Alexandre%20Delivet"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 11_Jul_2013\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Bertrand DIARD",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Bertrand_DIARD",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Bertrand_DIARD/M_Bertrand_DIARD-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Bertrand_DIARD/M_Bertrand_DIARD-original.jpg",
            "canonical_social_handle": "Bertrand%20Diard",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Bertrand%20Diard"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 23_Dec_2011\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Esteban Bayro-Kaiser",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-34-55/backups/Esteban_Bayro_Kaiser",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-34-55/backups/Esteban_Bayro_Kaiser/Esteban_Bayro_Kaiser-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-34-55/backups/Esteban_Bayro_Kaiser/Esteban_Bayro_Kaiser-original.jpg",
            "canonical_social_handle": "estebanbayrokaiser",
            "canonical_linkedin_url": "https://www.linkedin.com/in/estebanbayrokaiser"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Pierre SAUREL",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_SAUREL",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_SAUREL/M_Pierre_SAUREL-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Pierre_SAUREL/M_Pierre_SAUREL-original.jpg",
            "canonical_social_handle": "christian-gilbert-19216051",
            "canonical_linkedin_url": "https://www.linkedin.com/in/christian-gilbert-19216051"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "M Maxime PICAT",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Maxime_PICAT",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Maxime_PICAT/M_Maxime_PICAT-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-32-05/backups/M_Maxime_PICAT/M_Maxime_PICAT-original.jpg",
            "canonical_social_handle": "Maxime%20Picat",
            "canonical_linkedin_url": "https://www.linkedin.com/in/Maxime%20Picat"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\nLinkedIn_Connection_Since: 06_Jun_2015\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Fiona Darmon",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-47-11/backups/Fiona_Darmon",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-47-11/backups/Fiona_Darmon/Fiona_Darmon-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-08_02-47-11/backups/Fiona_Darmon/Fiona_Darmon-original.jpg",
            "canonical_social_handle": "fionadarmon",
            "canonical_linkedin_url": "https://www.linkedin.com/in/fionadarmon"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Nicolas MOYNIER",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Nicolas_MOYNIER",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Nicolas_MOYNIER/Nicolas_MOYNIER-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Nicolas_MOYNIER/Nicolas_MOYNIER-original.jpg",
            "canonical_social_handle": "nicolas-moynier-11628461",
            "canonical_linkedin_url": "https://www.linkedin.com/in/nicolas-moynier-11628461"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    },
    {
        "contact_name": "Marc Knoll",
        "original_backup_dir": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Marc_Knoll",
        "restore": {
            "note_from_file": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Marc_Knoll/Marc_Knoll-original.txt",
            "urls_to_remove_containing": [
                "linkedin.com"
            ],
            "photo_path": "/Users/pdewost/Documents/Personnel/Developpement/macOS Contacts Management/LSAMC - LinkedIn Sync Agent for macOS Contacts/logs/sessions/run_2026-03-07_14-48-13/backups/Marc_Knoll/Marc_Knoll-original.jpg",
            "canonical_social_handle": "marc-knoll-a0bb5a17",
            "canonical_linkedin_url": "https://www.linkedin.com/in/marc-knoll-a0bb5a17"
        },
        "sync_block_to_append": "<Linkedin-AI-sync 2026-03-09 Restore>\n</Linkedin-AI-sync>"
    }
]

def main():
    logger.info(f"{'='*60}")
    logger.info(f"LSAM RESTORE-DAMAGED-GROUP: Bulk Restoration (20 Targets)")
    logger.info(f"Session: {SESSION_DIR}")
    logger.info(f"Target count: {len(RESTORE_TARGETS)}")
    logger.info(f"{'='*60}")

    bridge = ContactMacOSBridge(mode="FULL")
    all_results = []

    for target in RESTORE_TARGETS:
        try:
            res = restore_contact(target, bridge)
            all_results.append(res)
        except Exception as e:
            logger.error(f"Critical error restoring {target['contact_name']}: {e}")
            all_results.append({"name": target['contact_name'], "success": False, "error": str(e)})

    # Summary
    logger.info(f"\n{'='*60}")
    logger.info("FINAL SUMMARY")
    logger.info(f"{'='*60}")
    for r in all_results:
        status = "✅ OK" if r.get("success") else "⚠️  PARTIAL/FAIL"
        logger.info(
            f"{status} | {r.get('name')}\n"
            f"         Restored:  {r.get('fields_restored', [])}\n"
            f"         Failed:    {r.get('fields_failed', [])}\n"
            f"         V-Passed:  {r.get('verification_passed', [])}\n"
            f"         V-Failed:  {r.get('verification_failed', [])}\n"
            f"         Error:     {r.get('error', 'None')}"
        )

    summary_path = os.path.join(SESSION_DIR, "damaged_restore_summary.json")
    with open(summary_path, "w") as f:
        json.dump(all_results, f, indent=2, default=str)
    logger.info(f"\nFull session log: {log_file}")
    logger.info(f"Backups saved to: {BACKUP_DIR}")
    logger.info(f"Summary JSON:     {summary_path}")

if __name__ == "__main__":
    main()
