
import os
import json
import logging
import datetime
import sys
from pathlib import Path
from typing import List, Dict, Any, Optional
import subprocess

# --- Path Initialization ---
CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = CURRENT_DIR.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Configure Logging
LOG_DIR = PROJECT_ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_DIR / "audit_manager.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("AuditManager")

PLAYLIST_FILE = PROJECT_ROOT / "data" / "audit_playlist.json"

class AuditManager:
    def __init__(self):
        try:
            from src.bridge.contact_macos import ContactMacOSBridge
            # Utilize FULL mode to allow writing timestamps
            self.bridge = ContactMacOSBridge(mode="FULL")
            logger.info("Bridge initialized for Audit.")
        except ImportError as e:
            logger.error(f"Could not import Bridge: {e}")
            raise

        self.playlist: List[Dict] = []
        self.current_idx = 0

    def load_playlist(self):
        """Loads the audit playlist generated by the script."""
        if not PLAYLIST_FILE.exists():
            logger.error("Playlist not found. Run generate_audit_playlist.py first.")
            return

        try:
            with open(PLAYLIST_FILE, 'r') as f:
                self.playlist = json.load(f)
            logger.info(f"Loaded {len(self.playlist)} items for audit.")
        except Exception as e:
            logger.error(f"Failed to load playlist: {e}")
            self.playlist = []

    # --- AppleScript UI Helpers (Ported from StagedManager) ---
    def _run_script(self, script: str) -> str:
        """Runs an AppleScript and returns stdout (or CANCEL on error)."""
        try:
            res = subprocess.run(
                ["osascript", "-e", script],
                capture_output=True, text=True, check=True
            )
            return res.stdout.strip()
        except subprocess.CalledProcessError as e:
            logger.error(f"AppleScript Error: {e.stderr}")
            return "CANCEL"

    def _show_dialog(self, title: str, text: str, buttons: List[str], default: str = None) -> str:
        btns_str = "{" + ", ".join([f'"{b}"' for b in buttons]) + "}"
        default_str = f'default button "{default}"' if default else ""
        # Escape text for AppleScript
        safe_text = text.replace('"', '\\"').replace('\n', '\\n')
        safe_title = title.replace('"', '\\"')
        
        script = f'''
        tell application "System Events"
            activate
            delay 0.5
            set userChoice to button returned of (display dialog "{safe_text}" with title "{safe_title}" buttons {btns_str} {default_str} with icon note)
        end tell
        return userChoice
        '''
        return self._run_script(script)
        
    def _input_dialog(self, title: str, prompt: str, default: str = "") -> str:
        safe_prompt = prompt.replace('"', '\\"')
        safe_default = default.replace('"', '\\"')
        script = f'''
        tell application "System Events"
            activate
            delay 0.5
            set userEntry to text returned of (display dialog "{safe_prompt}" with title "{title}" default answer "{safe_default}" buttons {{"Cancel", "OK"}} default button "OK")
        end tell
        return userEntry
        '''
        return self._run_script(script)

    def _choose_from_list(self, prompt: str, items: List[str], title: str = "Select Option") -> str:
        safe_items = [i.replace('"', '\\"') for i in items]
        items_str = "{" + ", ".join([f'"{i}"' for i in safe_items]) + "}"
        safe_prompt = prompt.replace('"', '\\"').replace('\n', '\\n')
        safe_title = title.replace('"', '\\"')
        
        script = f'''
        tell application "System Events"
            activate
            delay 0.5
            set userSelection to choose from list {items_str} with title "{safe_title}" with prompt "{safe_prompt}"
        end tell
        if userSelection is false then return "CANCEL"
        return item 1 of userSelection
        '''
        return self._run_script(script)

    def run_mac_interactive(self):
        """Main Loop using macOS Dialogs."""
        self.load_playlist()
        if not self.playlist:
            self._show_dialog("Audit Manager", "No items found in playlist.", ["OK"])
            return

        total = len(self.playlist)
        
        while self.current_idx < total:
            item = self.playlist[self.current_idx]
            cid = item.get("id")
            
            # 1. Select Contact in App
            try:
                self.bridge.select_contact(cid)
            except Exception as e:
                logger.error(f"Failed to select {cid}: {e}")

            # 2. Prepare View
            # We need a concise summary for the dialog
            view_text = (
                f"AUDIT {self.current_idx + 1}/{total}\n"
                f"Type: {item['category']}\n"
                f"Reason: {item['reason']}\n"
                f"Name: {item['name']}\n"
                "----------------\n"
                "Select 'Verify' to add stamp.\n"
                "Select 'Flag' to report issue."
            )
            
            # 3. Show Dialog
            # CRITICAL FIX v1.1: AppleScript only allows 3 buttons.
            choice = self._show_dialog(
                f"Reviewing: {item['name']}",
                view_text,
                ["More Actions...", "Flag...", "Verify"],
                default="Verify"
            )
            
            if choice == "More Actions...":
                action = self._handle_more_actions(item)
                if action == "QUIT":
                    break
                elif action == "SKIP":
                    self.current_idx += 1
                # Else loop back
                continue
                
            elif choice == "Verify":
                self._stamp_contact(cid, "VERIFIED", item['reason'])
                self.current_idx += 1
                
            elif choice == "Flag...":
                if self._handle_flagging_flow(cid):
                    self.current_idx += 1
                # If flow returns False (Cancel), loop back

        self._show_dialog("Audit Complete", "End of playlist reached.", ["OK"])

    def _handle_more_actions(self, item: Dict) -> str:
        """More Actions Menu"""
        cid = item.get("id")
        options = [
            "⏭️ Skip to Next",
            "🛑 Quit Audit",
            "📂 Open Vault Folder",
            "🔗 Open LinkedIn Profile",
            "📝 View Raw JSON",
            "🔄 Resync (Add to Force Queue)",
            "🗑️ Discard (False Match)"
        ]
        
        # Uses standard choose from list
        menu_str = "{" + ", ".join([f'"{o}"' for o in options]) + "}"
        script = f'''
        tell application "System Events"
            activate
            delay 0.5
            set userSelection to choose from list {menu_str} with title "More Actions"
        end tell
        if userSelection is false then return "CANCEL"
        return item 1 of userSelection
        '''
        selection = self._run_script(script)
        
        if selection == "CANCEL": return "CONTINUE"

        if selection.startswith("⏭️"):
             return "SKIP"
        elif selection.startswith("🛑"):
             return "QUIT"
        elif selection.startswith("📂"):
            subprocess.run(["open", item['path']])
        elif selection.startswith("🔗"):
            # Need to fetch URL from profile.json
            try:
                with open(item['path'], 'r') as f:
                    prof = json.load(f)
                url = prof.get("linkedin_url")
                if url: subprocess.run(["open", url])
            except: pass
        elif selection.startswith("📝"):
            subprocess.run(["open", "-t", item['path']])
        elif selection.startswith("🔄"):
            self.bridge.add_to_group(cid, "script-LSAM-Force-Refresh")
            self._stamp_contact(cid, "FLAGGED", "Sent to Force Refresh")
            return "SKIP"
        elif selection.startswith("🗑️"):
             self._stamp_contact(cid, "FLAGGED", "Discarded / False Match")
             return "SKIP"
        
        return "CONTINUE"

    def _handle_flagging_flow(self, cid: str) -> bool:
        """Handles the flagging process with Handoff options."""
        # 1. Ask for Reason
        reason = self._input_dialog("Flagging Issue", "Enter reason (e.g. Wrong Profile, Old Info):", default="Wrong Profile")
        if reason == "CANCEL" or not reason: return False
        
        # 2. Ask for Action (Handoff)
        # 2. Ask for Action (Handoff) - Uses list to avoid 3-button limit
        action = self._choose_from_list(
            f"Reason: {reason}\nWhat should we do with this contact?",
            ["Just Flag", "Move to Manual Fix", "Resync", "Cancel"],
            title="Action Required"
        )
        
        if action == "Cancel": return False
        
        # 3. Apply Stamp
        self._stamp_contact(cid, "FLAGGED", reason)
        
        # 4. Apply Action
        if action == "Move to Manual Fix":
            self.bridge.add_to_group(cid, "script-LSAM-Manual-Fix")
            logger.info(f"Moved {cid} to Manual Fix.")
        elif action == "Resync":
            self.bridge.add_to_group(cid, "script-LSAM-Force-Refresh")
            logger.info(f"Moved {cid} to Force Refresh.")
            
        return True

if __name__ == "__main__":
    manager = AuditManager()
    manager.run_mac_interactive()
